In [1]:
# importing numpy library
import numpy as np

In [2]:
# Creating a NumPy array and Matrix

narray = np.array([1,2,3,4])
matrix = np.array([[1,2],[3,4]])
print(narray)
print(matrix)

[1 2 3 4]
[[1 2]
 [3 4]]


In [4]:
# Zero and One Array - np.zeros(shape, dtype) OR np.zeros(shape)
zarray = np.zeros(5)
oarray = np.ones(5)
print(zarray)
print(oarray)

# Zero and One Matrix 
zmatrix = np.zeros((3,3,3,3))
omatrix = np.ones((3,2))
print(zmatrix)
print(omatrix)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.eye(3,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

np.identity(5)

In [13]:
# Creating an array of 5 random integers between 1 and 10

arr = np.random.randint(1, 11, 5)
print(arr)

# Creating a N x N array of random floats between 0 and 1 (1 exclusive)
arr2 = np.random.rand(2, 2, 2)
print(arr2)

[1 1 3 9 6]
[[[0.90667807 0.17401235]
  [0.60219429 0.23384327]]

 [[0.62359803 0.91244891]
  [0.031957   0.31655992]]]


In [15]:
# ARANGE = np.arange(start, end, step_size)

a_array = np.arange(0,201,1)
print(a_array)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200]


In [95]:
# LINSPACE = np.linspace(start, end, no_of_elements)
# spacing bw elements = (end - start) / (no_of_elements - 1)

l_array = np.linspace(0,3,5)
print(l_array)

[0.   0.75 1.5  2.25 3.  ]


In [99]:
# np.RANDOM.RAND(N) - Array of N random floats between 0 and 1
r1_array = np.random.rand(20)
print(r1_array)

# np.RANDOM.RANDINT(a,b,N) - N random integers between a and b
r2_array = np.random.randint(1,50,15)   
print(r2_array)

[0.9408445  0.63310452 0.54151064 0.60303489 0.30466033 0.68857295
 0.99940099 0.36116024 0.68151086 0.44908478 0.77541341 0.63088356
 0.17017147 0.59891659 0.79199354 0.5605505  0.37453766 0.5581082
 0.50008057 0.65381531]
[36  2 37 40 22 28 34 13 18  6 26 40 30 19 24]


In [16]:
a = np.array([1,2,3,4])

In [17]:
# Basic statistical operations
print("Minimum:", np.min(a))
print("Maximum:", np.max(a))
print("Sum:",     np.sum(a))
print("Mean:",    np.mean(a))
print("Median:",  np.median(a))


Minimum: 1
Maximum: 4
Sum: 10
Mean: 2.5
Median: 2.5


In [135]:
# Custom 9x9 Matrix:
# 1 1 1 1 1 1 1 1 1
# 1 0 0 0 0 0 0 0 1
# 1 0 3 0 0 0 0 0 1
# 1 0 0 3 0 0 0 0 1
# 1 0 0 0 3 0 0 0 1
# 1 0 0 0 0 3 0 0 1
# 1 0 0 0 0 0 3 0 1
# 1 0 0 0 0 0 0 0 1
# 1 1 1 1 1 1 1 1 1

a = np.ones((9,9))
b = np.zeros((7,7))
c = np.identity(5) * 3
print(a)
print(b)
print(c)
a[1:8, 1:8] = b
print(a)
a[2:7,2:7] = c
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 3. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 3. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 3. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 3. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0