In [2]:
#import packages
import pandas as pd
import numpy as np
from sklearn. model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB


In [3]:
#import data
spam_df = pd.read_csv(r"C:\Users\KIIT0001\OneDrive\Documents\KRS class\spam_filter.csv")

In [5]:
#inspect data
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [10]:
#turn ham or spam to numerics
#creating a new column called spam
spam_df['spam'] = spam_df['Category'].apply(lambda x: 1 if x == 'spam' else 0)


In [8]:
spam_df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [14]:
#create our tran_test_split
X_train,X_test,y_train,y_test = train_test_split(spam_df.Message, spam_df.spam, test_size = 0.25)

In [16]:
#find the word count and store data as numerical matrix
cv = CountVectorizer()
X_train_count = cv.fit_transform(X_train.values)

In [18]:
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
#train
model =  MultinomialNB()
model.fit(X_train_count,y_train)


MultinomialNB()

In [27]:
#pre-test ham
email_ham = ["hey wanna meet up for the movie?"]
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)
#answer is zero which is not spam

array([0], dtype=int64)

In [28]:
#pre-test spam
email_spam = ["reward money click"]
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)
#answer is one which is spam

array([1], dtype=int64)

In [29]:
#test model
X_test_count = cv.transform(X_test)
model.score(X_test_count,y_test)

0.9798994974874372

In [30]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [31]:
y_pred = model.predict(X_test_count)

In [32]:
# Accuracy
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

Accuracy: 0.9798994974874372


In [33]:
# Precision
prec = precision_score(y_test, y_pred)
print("Precision:", prec)

Precision: 0.9668508287292817


In [34]:
# Recall
rec = recall_score(y_test, y_pred)
print("Recall:", rec)

Recall: 0.8883248730964467


In [35]:
# F1 Score
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

F1 Score: 0.9259259259259259


In [36]:
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", cm)


Confusion Matrix:
 [[1190    6]
 [  22  175]]
