In [12]:
#Importing Required Libraries

import pandas as pd
import numpy as np

In [13]:
#Importing dataset from skikit learn. This is taken from the online dataset

from sklearn.datasets import fetch_california_housing ##skikit learn library

In [14]:
dataset=fetch_california_housing()
dataset
##ml models have targets(dependent) and features(independent)==> Supervised learning

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [15]:
#Converting it into Dataframe - Independent Variables

df_x = pd.DataFrame(dataset.data)# the value of features are provided. The features are columns that are independent and targets are the independent ones.
df_x

0     1         2         3       4         5      6       7
0      8.3252  41.0  6.984127  1.023810   322.0  2.555556  37.88 -122.23
1      8.3014  21.0  6.238137  0.971880  2401.0  2.109842  37.86 -122.22
2      7.2574  52.0  8.288136  1.073446   496.0  2.802260  37.85 -122.24
3      5.6431  52.0  5.817352  1.073059   558.0  2.547945  37.85 -122.25
4      3.8462  52.0  6.281853  1.081081   565.0  2.181467  37.85 -122.25
...       ...   ...       ...       ...     ...       ...    ...     ...
20635  1.5603  25.0  5.045455  1.133333   845.0  2.560606  39.48 -121.09
20636  2.5568  18.0  6.114035  1.315789   356.0  3.122807  39.49 -121.21
20637  1.7000  17.0  5.205543  1.120092  1007.0  2.325635  39.43 -121.22
20638  1.8672  18.0  5.329513  1.171920   741.0  2.123209  39.43 -121.32
20639  2.3886  16.0  5.254717  1.162264  1387.0  2.616981  39.37 -121.24

[20640 rows x 8 columns]

In [16]:
#Adding Column names from dataset - Independent/Features

df_x.columns=dataset.feature_names
df_x

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [17]:
#Dependent Variable/target

df_y = pd.DataFrame(dataset.target, columns=dataset.target_names)
df_y

MedHouseVal
0            4.526
1            3.585
2            3.521
3            3.413
4            3.422
...            ...
20635        0.781
20636        0.771
20637        0.923
20638        0.847
20639        0.894

[20640 rows x 1 columns]

In [23]:
#Independent features and Dependent features

x=df_x#dependent
y=df_y#independent
#preprocessing is complete till this part

In [26]:
#Train Test Split

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,random_state=42)#it means 70%training and 30% testing; random state is used for shufling
# 70% of x and 70% of y is taken, not seperate parts of individuals are taken.

In [27]:
#basically we are pre-processing the data.

In [31]:
#Standardizing dataset
# we are doing weighing. It is for the variations between the values. If the values are high, the model assumes that it has higher priority and take/gives its values, we standardizr to increase variation

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
##Scalar = (x-(miu))/sigma

In [32]:
#Fitting in Standard Scaler
#fit_transform --> taking te values from the formuales, it takes few values. Transform--> it takes and replaces the values from the standardized value to the initial values
x_train=scaler.fit_transform(x_train)#the training data is taken and 
x_test=scaler.transform(x_test)# we are taking the mean values of train and replace it with the values and then fit it. We are using the same test scale

In [33]:
x_train

array([[-0.53219072, -0.67982045, -0.42260285, ..., -0.08931351,
        -1.33951218,  1.2453071 ],
       [ 0.17099313, -0.36270041,  0.07313842, ..., -0.04479956,
        -0.49669489, -0.27749403],
       [-0.40289308, -1.1555005 ,  0.17585475, ..., -0.07522769,
         1.68994775, -0.70687401],
       ...,
       [-0.49476107,  0.58865969, -0.59153751, ...,  0.01719968,
        -0.75890471,  0.60123711],
       [ 0.96714739, -1.07622049,  0.39014836, ...,  0.00482034,
         0.90331827, -1.18618191],
       [-0.6831692 ,  1.85713982, -0.82961574, ..., -0.08166962,
         0.99228232, -1.41585028]])

In [47]:
x_test

array([[-1.15264088, -0.28342041, -0.50778869, ...,  0.06127476,
         0.1916059 ,  0.28669131],
       [-0.70637243,  0.11297964, -0.16250235, ..., -0.03551513,
        -0.23916739,  0.06201573],
       [-0.20829043,  1.85713982, -0.59543491, ..., -0.1421501 ,
         1.00632928, -1.42583586],
       ...,
       [-0.11909974, -1.47262053,  0.02608373, ...,  0.03461179,
         1.01569391, -0.84667215],
       [-0.43302578, -0.91766047, -0.84868799, ..., -0.04075214,
        -0.7027169 ,  0.67113618],
       [ 0.13351099,  0.50937968,  0.18106665, ..., -0.01082557,
        -0.8057279 ,  0.78097757]])

In [34]:
y_test

MedHouseVal
20046      0.47700
3024       0.45800
15663      5.00001
20484      2.18600
9814       2.78000
...            ...
13512      0.67300
10842      2.18400
16559      1.19400
5786       2.09800
7061       1.93800

[6193 rows x 1 columns]

In [35]:
y_train

MedHouseVal
14689      1.69700
17323      2.59800
10056      1.36100
15750      5.00001
15283      2.81300
...            ...
11284      2.29200
11964      0.97800
5390       2.22100
860        2.83500
15795      3.25000

[14447 rows x 1 columns]

In [41]:
#Model Initialization

from sklearn.linear_model import LinearRegression
model=LinearRegression()#model reinitialization. We have not provided the data to the model 

In [42]:
#Fitting my dataset into the model 

model.fit(x_train,y_train)

LinearRegression()

In [43]:
#Prediction

model_pred=model.predict(x_test)#We used x_test as we had kept that seperate for proper prediction as if we give the traiing data for testing it would always give us the correct answer.
model_pred

array([[0.72606026],
       [1.76744676],
       [2.71090329],
       ...,
       [1.57370312],
       [1.82742973],
       [2.137662  ]])

In [45]:
#Evaluation 

from sklearn.metrics import mean_squared_error#mean_squared_error --> it is a built in feature

rmse = np.sqrt(mean_squared_error(y_test, model_pred))#(actual-predicted)/predicted; we can improve its accuracy by dealing with random state(1-100)
rmse

np.float64(0.7283446298926005)